### ISSUE TITLE
Unable to force `.val()` when accessing ref property

### ISSUE THREAD

**Issue by cebartling** [firebase/bolt#186] opened 2017-01-05 22:02 UTC
## Input
Given bolt file containing the following content:

```
function isAssociatedWithSharedAsset(auth, assetId) {
    return root.child('users').child(auth.uid).child('shared_asset_refs').child(assetId) != null;
}


path /organizations/{organizationId}/collections/{collectionId} {
    read() {
        isAssociatedWithSharedAsset(auth, this.asset_id)
    }
    write() {
        isAssociatedWithSharedAsset(auth, this.asset_id)
    }
}
```

## Actual output
Compiling that to the desired JSON format yields:

```
{
  "rules": {
    "organizations": {
      "$organizationId": {
        "collections": {
          "$collectionId": {
            ".read": "root.child('users').child(auth.uid).child('shared_asset_refs').child(data.child('asset_id')) != null",
            ".write": "newData.parent().parent().parent().parent().child('users').child(auth.uid).child('shared_asset_refs').child(newData.child('asset_id')) != null"
          }
        }
      }
    }
  }
}
```

That resulting JSON structure is invalid and will not publish in the Firebase Console. In particular, `.child(data.child('asset_id'))` will not publish in the Firebase Console

## Desired output

I was expecting the following JSON structure (Note that the `!= null` not converting to `.exists()` has been separately filed as an issue):

```
{
  "rules": {
    "organizations": {
      "$organizationId": {
        "collections": {
          "$collectionId": {
            ".read": "root.child('users').child(auth.uid).child('shared_asset_refs').child(data.child('asset_id').val()).exists()",
            ".write": "newData.parent().parent().parent().parent().child('users').child(auth.uid).child('shared_asset_refs').child(newData.child('asset_id').val()).exists()"
          }
        }
      }
    }
  }
}
```

The `.child(newData.child('asset_id').val())` change will now publish in the Firebase console.

**Comment by mckoss** [comment] 2017-01-31 19:27
Duplicate of #185 ?

**Closed** 2017-01-31 19:27 UTC
Labels: duplicate
