### ISSUE TITLE
Why not Typescript

### ISSUE THREAD

**Issue by notsonotso** [firebase/bolt#197] opened 2017-06-19 20:40 UTC
Bolt is a great idea, but you could just as well have defined the rules in pure Typescript. The benefits should be obvious.

My pet idea is rules for automatic schema evolution. Just push it to cloud functions, and the schema is evolved according to the rules lazily. Stuff like that. And people already know Typescript and would be able to actually write these things.

How about it?

**Comment by adamduren** [comment] 2017-08-11 14:00
This along a similar vein as #197. I do think we need something to cut down on the repetition and potential for errors caused by maintaining multiple types of validation formats. However I don't think requiring developers to adopt a different language such as TypeScript is the best approach.

I had a [similar idea](https://github.com/firebase/bolt/issues/150#issuecomment-321819471) that proposes to use the JSON schema standard to generate Bolt types. There is already a project that transpiles JSON schema definitions into TypeScript interfaces and if we had a way to transpile JSON schema to bolt it seems like it would accomplish consistency across a project.

**Comment by notsonotso** [comment] 2017-08-11 17:23
@adamduren makes sense, thanks.

**Comment by rockwotj** [comment] 2017-10-21 22:36
Closing this in favor of #150

**Closed by rockwotj** 2017-10-21 22:36 UTC
